{{- range .Values.scheduledPolicies }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "cloud-custodian-cron.fullname" $ }}-{{ .name }}"
  labels:
   {{- include "cloud-custodian-cron.labels" $ | nindent 4 }}
data:
  policies.yaml: |-
    {{- if .vars }}
    vars:
      {{- toYaml .vars | nindent 6 }}
    {{- end }}
    policies:
      {{- toYaml .policies | nindent 4 }}
{{- end }}
