{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloud-custodian-cron.fullname" . }}
  labels:
    app: {{ include "cloud-custodian-cron.name" . }}
    chart: {{ include "cloud-custodian-cron.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
{{- if .Values.secrets.aws }}
  accessKey: {{ required "accessKey is required if AWS configuration is specified." .Values.secrets.aws.accessKey | b64enc | quote }}
  secretKey: {{ required "secretKey is required if AWS configuration is specified." .Values.secrets.aws.secretKey | b64enc | quote }}
  defaultRegion: {{ required "defaultRegion is required if AWS configuration is specified." .Values.secrets.aws.defaultRegion | b64enc | quote }}
{{- end }}
{{- if .Values.secrets.azure }}
  tenantID: {{ required "tenantID is required if Azure configuration is specified." .Values.secrets.azure.tenantID | b64enc | quote }}
  subscriptionID: {{ required "subscriptionID is required if Azure configuration is specified." .Values.secrets.azure.subscriptionID | b64enc | quote }}
  clientID: {{ required "clientID is required if Azure configuration is specified." .Values.secrets.azure.clientID | b64enc | quote }}
  clientSecret: {{ required "clientSecret is required if Azure configuration is specified." .Values.secrets.azure.clientSecret | b64enc | quote }}
{{- end }}
{{- end }}
